// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.3
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMMULT_ACCEL_CORE_H
#define XMMULT_ACCEL_CORE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#include "xmmult_accel_core_CONTROL_BUS.h"

/**************************** Type Definitions ******************************/
typedef struct {
    u16 DeviceId; // currently not used
    u32 Control_bus_BaseAddress;
} XMmult_accel_core_Config;

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XMmult_accel_core;

/***************** Macros (Inline Functions) Definitions *********************/
#define XMmult_accel_core_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))

#define XMmult_accel_core_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))

/************************** Function Prototypes *****************************/
int XMmult_accel_core_Initialize(XMmult_accel_core *InstancePtr, XMmult_accel_core_Config *ConfigPtr);

void XMmult_accel_core_Start(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_IsDone(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_IsIdle(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_IsReady(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_EnableAutoRestart(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_DisableAutoRestart(XMmult_accel_core *InstancePtr);


void XMmult_accel_core_InterruptGlobalEnable(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_InterruptGlobalDisable(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_InterruptEnable(XMmult_accel_core *InstancePtr, u32 Mask);
void XMmult_accel_core_InterruptDisable(XMmult_accel_core *InstancePtr, u32 Mask);
void XMmult_accel_core_InterruptClear(XMmult_accel_core *InstancePtr, u32 Mask);
u32 XMmult_accel_core_InterruptGetEnabled(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_InterruptGetStatus(XMmult_accel_core *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
